### ISSUE TITLE
The last step in your work

### ISSUE THREAD

**Issue by HA-sala** [gaolinorange/SDMNET_stamp#1]
Thank you for your work!
The last step in your work, Open those meshes in meshlab and you will see the reproduced results for Fig.1 in the original paper. I've generated a lot of meshes, but I can only use the Meshlab to open an OBJ file for one part of the model. Only armrest of chair, only leg of chair, not is a Full chair. So can you elaborate on how to get a full chair, thank you!

**Comment by tommaoer** [comment]
Thanks for your interest! For the issue, you can run the script '''GetOptimizedObj''' to get a full chair, which can merge the parts into a full shape by an optimization(illustrated in our paper). The usage is introduced in step [2] of the readme. 
If you have further questions, please feel free to contact me.

**Comment by cravisjan97** [comment]
I am using GetOptimizedObj function but I get the following error

```
Error using reshape
Number of elements must not change. Use [] as one of the size inputs to automatically calculate the
appropriate size for that dimension.

Error in GetOptimizedObj (line 77)
            code = reshape(mat.symmetry_feature(i, :), n, 2*n+9);
```

**Comment by tommaoer** [comment]
I think you should check the size of the matrix. BTW, which category was recovering?

**Comment by HA-sala** [comment]
@cravisjan97  Because "n", from  n = size(part_names, 2) , is the wrong number. In getlabel.m( line 4),  to delete  'armrest2_1', 'armrest2_2' ( part_names of chair )

**Comment by tommaoer** [comment]
@HA-sala I think you have become a master on this code. Thanks for your detailed explanations! :)

**Comment by cravisjan97** [comment]
> I get this error ```Undefined function 'quadprog' for input arguments of type 'double'.``` when I run ```GetOptimizedObj``` for Chairs. How do I solve this?

 I just realized that I need the Optimization toolbox to run the code.
