### ISSUE TITLE
The pre-trained checkpoint link is broken

### ISSUE THREAD

**Issue by chengzg** [gaolinorange/SDMNET_stamp#3]
Hi,

@gaolinorange, Thanks for the great work. I am interested to explorer more on this paper. 

However, it seems the checkpoint downloading link is broken. Could you help fix it? 

![image](https://user-images.githubusercontent.com/5573089/102315525-425ab680-3faf-11eb-9b11-8a350fcad858.png)

Thanks & Regards,
Spencer

**Comment by ZPDou98** [comment]
We updated the checkpoint download permission. Please check. @chengzg

**Comment by chengzg** [comment]
@shinexg So fast! Thanks. Downloading now.
