### ISSUE TITLE
Unable to reproduce the result following the "Reproduce" instruction

### ISSUE THREAD

**Issue by chengzg** [gaolinorange/SDMNET_stamp#5]
Hi,

@tommaoer 

Sorry to post the question here. Here i am not able to reproduce the result by following the 'Reproduce' instruction on the github page. I used the provided data and check point, and follow the exact steps on the page. My optimized result is very bad. For example, as iteration 199: 

unoptimized_199.obj:
![image](https://user-images.githubusercontent.com/5573089/104173177-5a9fe300-5440-11eb-91f5-3163235b7ccc.png)

optimized_199.obj **which is even worse**
![image](https://user-images.githubusercontent.com/5573089/104173277-7c996580-5440-11eb-8147-da73e147f454.png)
![image](https://user-images.githubusercontent.com/5573089/104173458-c3875b00-5440-11eb-8827-8b1c90cb61ad.png)

Was there something not provided? Thanks a lot for any help provided.

Thanks & Regards,
Spencer

**Comment by shinxg** [comment]
We updated it. Please update your local repo.

**Comment by chengzg** [comment]
Hi,

@shinxg
Thanks very much for the update. After updating the code, i do get result similar to what is presented in the Paper.

However, by looking at the code changes, i feel the update is kind of "Hard Coded" towards for the particular Chair category with 8 segments? And from the code the change seems affect the plane interpolation? Is it expected to do this kind of customisation for different categories?

Again, thanks a lot for your reply.

Thanks & Regards,
Spencer

**Comment by shinxg** [comment]
Yes, we add prior info before optimizing. @chengzg
