### ISSUE TITLE
Can not reproduce chair correctly by following the steps in README.md 

### ISSUE THREAD

**Issue by susan31213** [gaolinorange/SDMNET_stamp#9]
This is a great work! I am interested in it very much. 
I tried to reproduce by following the steps in **README.md.** I got the right result of plane but wrong result with chair data.
The armrests' positions are wrong(like the picture) and they are different from the **Fig.1** in the paper.
![Screenshot from 2021-03-26 17-14-55](https://user-images.githubusercontent.com/16774199/112609823-fa251d00-8e56-11eb-896d-8cdb0fe1ff29.png)
How can I get the correct result?

Thanks a lot if any help provided.

Thanks & Regards,
Susan

**Comment by susan31213** [comment]
Update:
Here is the output when I ran
```
cd ../chair_reproduce
CUDA_VISIBLE_DEVICES='' python ./test_stacknewvae.py --output_dir ./05060123_6863bin_1-joint_1-l0_100.0-l2_10.0-l3_1.0-l4_0.001-model_chair-trcet_1.0 --interids '4e664dae1bafe49f19fb4103277a6b93' '1c17cc67b8c747c3febad4f49b26ec52' '2bbf00f0c583fd8a4b3c42e318f3affc'
```
[log.txt](https://github.com/gaolinorange/SDMNET_stamp/files/6210723/log.txt)

**Comment by shinxg** [comment]
It seems that you did not run the optimization process. You should run post-process after interpolation.

``GetOptimizedObj('../python/chair_reproduce/05060123_6863bin_1-joint_1-l0_100.0-l2_10.0-l3_1.0-l4_0.001-model_chair-trcet_1.0/interpolation100000', 'chair', 2, 0, 0)``

**Comment by susan31213** [comment]
Hi shinxg,

Thanks for your reply! I tried to run post-process(`GetOptimizedObj('../python/chair_reproduce/05060123_6863bin_1-joint_1-l0_100.0-l2_10.0-l3_1.0-l4_0.001-model_chair-trcet_1.0/interpolation100000', 'chair', 2, 0, 0)`), but there are some problem in matlab codes.
I also tried to fix them and create a pull request, but I still got a different result from **Fig.1**:
![image](https://user-images.githubusercontent.com/16774199/112668594-aa1b7a00-8e99-11eb-94cd-c142058c85cb.png)
Next, I tried to set `use struct = 1`(e.g. `GetOptimizedObj('../python/chair_reproduce/05060123_6863bin_1-joint_1-l0_100.0-l2_10.0-l3_1.0-l4_0.001-model_chair-trcet_1.0/interpolation100000', 'chair', 2, 1, 0)`) and got this:
![image](https://user-images.githubusercontent.com/16774199/112668898-fcf53180-8e99-11eb-8063-4cb3b547768c.png)
The armrests are shifted but still in a wrong position. 😢 
I also check the origin model and it looks like this:
![image](https://user-images.githubusercontent.com/16774199/112669505-c2d85f80-8e9a-11eb-8e87-8f2680c8607e.png)
Do you have any idea about the reason why cannot get the correct armrests' positions?

Thanks for your time to read this.

Regards,
Susan

**Comment by shinxg** [comment]
Sorry for the late reply. We updated a new version. Please update your local repo and run again.

**Comment by susan31213** [comment]
It works! Thanks for the update!
